//
//  ResultsView.swift
//  Mactenna
//
//  Displays the output of an OpenNEC simulation run.
//  Phase 3 shows the formatted NEC text report and captured log lines.
//  Phase 4 will add a 3D radiation pattern tab.
//

import SwiftUI

// MARK: – ResultsView

struct ResultsView: View {

    /// Reference to the deck so we can request additional pattern calculations.
    @ObservedObject var deck: NECDeck

    private var result: SimulationResult? { deck.simulationResult }
    private var isRunning: Bool { deck.isRunning }

    @State private var selectedTab: ResultTab = .pattern

    /// Points generated by a full‑sphere pattern run (step ~5°).
    @State private var fullPatternPoints: [SimulationResult.RadiationPoint] = []
    @State private var isComputingPattern: Bool = false

    var body: some View {
        VStack(spacing: 0) {
            if isRunning {
                runningPlaceholder
            } else if let result {
                tabHeader
                Divider()
                tabContent(result)
            } else {
                idlePlaceholder
            }
        }
        .onChange(of: selectedTab) { _, tab in
            if tab == .pattern {
                startPatternComputationIfNeeded()
            }
        }
        .onReceive(deck.$simulationResult) { _ in
            if selectedTab == .pattern {
                startPatternComputationIfNeeded()
            }
        }
        .onAppear {
            if selectedTab == .pattern {
                startPatternComputationIfNeeded()
            }
        }
    }

    /// Kick off a full-sphere pattern run if we haven’t already done so.
    private func startPatternComputationIfNeeded() {
        guard Preferences.shared.patternAutoRun else { return }
        guard fullPatternPoints.isEmpty, !isComputingPattern else { return }
        isComputingPattern = true
        deck.computeFullPattern(stepDegrees: Preferences.shared.simDefaultStepDegrees) { pts in
            self.fullPatternPoints = pts
            self.isComputingPattern = false
        }
    }

    // MARK: – Idle / running placeholders

    private var idlePlaceholder: some View {
        VStack(spacing: 8) {
            Image(systemName: "waveform.path.ecg")
                .font(.system(size: 48))
                .foregroundStyle(.secondary)
            Text("No Results")
                .font(.title2)
                .foregroundStyle(.secondary)
            Text("Press Run (▶) to simulate this deck.")
                .font(.callout)
                .foregroundStyle(.tertiary)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    private var runningPlaceholder: some View {
        VStack(spacing: 12) {
            ProgressView()
                .scaleEffect(1.5)
            Text("Running simulation…")
                .font(.callout)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: – Tab header

    private var tabHeader: some View {
        HStack(spacing: 0) {
            ForEach(ResultTab.allCases) { tab in
                Button {
                    selectedTab = tab
                } label: {
                    Text(tab.label)
                        .font(.system(size: 12, weight: selectedTab == tab ? .semibold : .regular))
                        .padding(.vertical, 6)
                        .padding(.horizontal, 12)
                        .background(
                            selectedTab == tab
                                ? Color.accentColor.opacity(0.12)
                                : Color.clear,
                            in: RoundedRectangle(cornerRadius: 6)
                        )
                }
                .buttonStyle(.plain)
            }
            Spacer()
        }
        .padding(.horizontal, 8)
        .padding(.top, 4)
    }

    // MARK: – Tab content

    @ViewBuilder
    private func tabContent(_ result: SimulationResult) -> some View {
        // With only the pattern tab available the switch is trivial.
        patternTab(result)
    }


    private func patternTab(_ result: SimulationResult) -> some View {
        // Determine which set of points to display before building views.
        let pts: [SimulationResult.RadiationPoint]
        if !fullPatternPoints.isEmpty {
            pts = fullPatternPoints
        } else {
            pts = result.radiationPattern
        }
        // compute gain range from whichever list we're using
        let maxG: Double = pts.map { $0.gain }.max() ?? result.patternMaxGain
        let minG: Double = pts.map { $0.gain }.min() ?? 0

        return ZStack {
            if pts.isEmpty {
                VStack(spacing: 8) {
                    Image(systemName: "xmark.octagon")
                        .font(.system(size: 32))
                        .foregroundStyle(.secondary)
                    Text("No radiation pattern data")
                        .foregroundStyle(.secondary)
                    Text("Use Run to simulate or wait for full‑sphere computation.")
                        .font(.caption)
                        .foregroundStyle(.tertiary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                PatternView(points: pts, maxGain: maxG)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            }

            // legend overlay (only when we actually have points)
            if !pts.isEmpty {
                VStack {
                    Spacer()
                    GainLegend(minGain: minG, maxGain: maxG)
                        .padding(8)
                        .background(Color(.windowBackgroundColor).opacity(0.7))
                        .cornerRadius(6)
                        .padding(8)
                }
            }

            if isComputingPattern {
                ProgressView("Computing pattern…")
                    .progressViewStyle(CircularProgressViewStyle())
                    .padding(8)
                    .background(Color(.windowBackgroundColor).opacity(0.8))
                    .cornerRadius(8)
            }
        }
    }
}

// MARK: – ResultTab

private enum ResultTab: String, CaseIterable, Identifiable {
    case pattern = "Pattern"

    var id: String { rawValue }
    var label: String { rawValue }
}

// MARK: – Legend view

/// Displays a small gradient bar showing the mapping from gain values to the
/// colours used in the PatternView.
private struct GainLegend: View {
    let minGain: Double
    let maxGain: Double

    var body: some View {
        VStack(spacing: 4) {
            HStack {
                Text(String(format: "%.1f dBi", minGain))
                    .font(.caption2)
                Spacer()
                Text(String(format: "%.1f dBi", maxGain))
                    .font(.caption2)
            }
            Rectangle()
                .fill(LinearGradient(
                    gradient: Gradient(colors: [
                        PatternView.swiftUIColor(forNorm: 0),
                        PatternView.swiftUIColor(forNorm: 1)
                    ]),
                    startPoint: .leading,
                    endPoint: .trailing))
                .frame(height: 8)
                .cornerRadius(4)
        }
        .padding(4)
    }
}

// MARK: – MonospaceTextView

/// NSViewRepresentable wrapping NSTextView for displaying large monospace text.
/// SwiftUI's Text/ScrollView combo degrades badly for long NEC output (~1000+ lines).
private struct MonospaceTextView: NSViewRepresentable {

    let text: String

    func makeNSView(context: Context) -> NSScrollView {
        let scrollView = NSTextView.scrollableTextView()
        if let tv = scrollView.documentView as? NSTextView {
            tv.isEditable      = false
            tv.isSelectable    = true
            tv.font            = NSFont.monospacedSystemFont(ofSize: 11, weight: .regular)
            tv.backgroundColor = NSColor.textBackgroundColor
            tv.textColor       = NSColor.textColor
            tv.string          = text
        }
        return scrollView
    }

    func updateNSView(_ scrollView: NSScrollView, context: Context) {
        guard let tv = scrollView.documentView as? NSTextView else { return }
        if tv.string != text {
            tv.string = text
            // Scroll to top on new result
            tv.scrollToBeginningOfDocument(nil)
        }
    }
}
