//
//  ResultsView.swift
//  Phase 3 shows the formatted NEC text report and captured log lines.
//  Phase 4 will add a 3D radiation pattern tab.
//

import SwiftUI
import SceneKit

// MARK: – ResultsView

struct ResultsView: View {

    /// Reference to the deck so we can request additional pattern calculations.
    @ObservedObject var deck: NECDeck
    /// Access the undo manager from environment (used when committing drags).
    @Environment(\.undoManager) private var undoManager
    /// Currently selected deck row, shared with the table view.
    @Binding var selectedIndex: Int?

    private var result: SimulationResult? { deck.simulationResult }
    private var isRunning: Bool { deck.isRunning }

    // start on geometry tab by default
    @State private var selectedTab: ResultTab = .geometry

    /// Points generated by a full‑sphere pattern run (step ~5°).
    @State private var fullPatternPoints: [SimulationResult.RadiationPoint] = []
    @State private var isComputingPattern: Bool = false
    // camera transform for geometry view, persisted across tab switches
    @State private var geometryCamera: SCNMatrix4? = nil

    var body: some View {
        VStack(spacing: 0) {
            // debug: monitor selection
            EmptyView().onChange(of: selectedIndex) {
                // selection change monitored for debugging previously
            }
            if isRunning {
                runningPlaceholder
            } else if let result {
                tabHeader
                Divider()
                tabContent(result)
            } else {
                idlePlaceholder
            }
        }
        .onChange(of: selectedTab) { _, tab in
            if tab == .pattern {
                startPatternComputationIfNeeded()
            }
        }
        .onReceive(deck.$simulationResult) { _ in
            if selectedTab == .pattern {
                startPatternComputationIfNeeded()
            }
        }
        .onAppear {
            if selectedTab == .pattern {
                startPatternComputationIfNeeded()
            }
        }
    }

    /// Kick off a full-sphere pattern run if we haven’t already done so.
    private func startPatternComputationIfNeeded() {
        guard Preferences.shared.patternAutoRun else { return }
        guard fullPatternPoints.isEmpty, !isComputingPattern else { return }
        isComputingPattern = true
        deck.computeFullPattern(stepDegrees: Preferences.shared.simDefaultStepDegrees) { pts in
            self.fullPatternPoints = pts
            self.isComputingPattern = false
        }
    }

    // MARK: – Idle / running placeholders

    private var idlePlaceholder: some View {
        VStack(spacing: 8) {
            Image(systemName: "waveform.path.ecg")
                .font(.system(size: 48))
                .foregroundStyle(.secondary)
            Text("No Results")
                .font(.title2)
                .foregroundStyle(.secondary)
            Text("Press Run (▶) to simulate this deck.")
                .font(.callout)
                .foregroundStyle(.tertiary)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    private var runningPlaceholder: some View {
        VStack(spacing: 12) {
            ProgressView()
                .scaleEffect(1.5)
            Text("Running simulation…")
                .font(.callout)
                .foregroundStyle(.secondary)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }

    // MARK: – Tab header

    private var tabHeader: some View {
        HStack(spacing: 0) {
            ForEach(ResultTab.allCases) { tab in
                Button {
                    selectedTab = tab
                } label: {
                    Text(tab.label)
                        .font(.system(size: 12, weight: selectedTab == tab ? .semibold : .regular))
                        .padding(.vertical, 6)
                        .padding(.horizontal, 12)
                        .background(
                            selectedTab == tab
                            ? Color.accentColor.opacity(0.12)
                            : Color.clear,
                            in: RoundedRectangle(cornerRadius: 6)
                        )
                }
                .buttonStyle(.plain)
            }
            Spacer()
        }
        .padding(.horizontal, 8)
        .padding(.top, 4)
    }

    // MARK: – Tab content

    @ViewBuilder
    private func tabContent(_ result: SimulationResult) -> some View {
        switch selectedTab {
        case .pattern:
            patternTab(result)
        case .geometry:
            geometryTab()
        case .smith:
            smithChartTab(result)
        }
    }


    private func patternTab(_ result: SimulationResult) -> some View {
        // Determine which set of points to display before building views.
        let pts: [SimulationResult.RadiationPoint]
        if !fullPatternPoints.isEmpty {
            pts = fullPatternPoints
        } else {
            pts = result.radiationPattern
        }
        // compute gain range from whichever list we're using
        let maxG: Double = pts.map { $0.gain }.max() ?? result.patternMaxGain
        let minG: Double = pts.map { $0.gain }.min() ?? 0

        // compose view with overlays
        return ZStack {
            if pts.isEmpty {
                VStack(spacing: 8) {
                    Image(systemName: "xmark.octagon")
                        .font(.system(size: 32))
                        .foregroundStyle(.secondary)
                    Text("No radiation pattern data")
                        .foregroundStyle(.secondary)
                    Text("Use Run to simulate or wait for full‑sphere computation.")
                        .font(.caption)
                        .foregroundStyle(.tertiary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                PatternView(points: pts, maxGain: maxG)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            }

            // legend overlay (only when we actually have points)
            if !pts.isEmpty {
                VStack {
                    Spacer()
                    GainLegend(minGain: minG, maxGain: maxG)
                        .padding(8)
                        .background(Color(.windowBackgroundColor).opacity(0.7))
                        .cornerRadius(6)
                        .padding(8)
                }
            }

            if isComputingPattern {
                ProgressView("Computing pattern…")
                    .progressViewStyle(CircularProgressViewStyle())
                    .padding(8)
                    .background(Color(.windowBackgroundColor).opacity(0.8))
                    .cornerRadius(8)
            }
        }
    }

    /// View displayed when the Geometry tab is selected.
    private func geometryTab() -> some View {
        // construct segments directly from deck rows so edits appear immediately
        let geomSegments: [GeometrySegment] =
            (0..<deck.cardCount).compactMap { idx in
                guard let row = deck.card(at: idx),
                      deck.isInGeometrySection(row: idx),
                      !row.isIgnored, !row.isInvisible else { return nil }
                switch row.cardCode {
                case "GW":
                    // network wire: F1–F3 = start, F4–F6 = end, F7 = radius
                    let start = SIMD3<Float>(Float(row.f[0]), Float(row.f[1]), Float(row.f[2]))
                    let end   = SIMD3<Float>(Float(row.f[3]), Float(row.f[4]), Float(row.f[5]))
                    let rad   = Float(row.f[6])
                    return GeometrySegment(start: start, end: end, cardIndex: idx, radius: rad)
                default:
                    return nil
                }
            }
        return ZStack {
            if geomSegments.isEmpty {
                VStack(spacing: 8) {
                    Image(systemName: "cube.box")
                        .font(.system(size: 32))
                        .foregroundStyle(.secondary)
                    Text("No geometry data")
                        .foregroundStyle(.secondary)
                    Text("Add cards or run a simulation with geometry information.")
                        .font(.caption)
                        .foregroundStyle(.tertiary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                GeometryView(geometry: geomSegments,
                         selectedCard: selectedIndex,
                         cameraTransform: $geometryCamera,
                         onSelect: { new in
                             selectedIndex = new
                         },
                         onDragCommit: { card, newStart, newEnd in
                             handleDragCommit(card: card, newStart: newStart, newEnd: newEnd)
                         })
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
    }

    /// Apply a position change resulting from a handle drag to the NEC deck.
    private func handleDragCommit(card: Int, newStart: SIMD3<Float>?, newEnd: SIMD3<Float>?) {
        print("commit drag card \(card) start=\(String(describing: newStart)) end=\(String(describing: newEnd))")
        if let before = deck.card(at: card) {
            print("  before: f=\(before.f)")
        }
        let snapshot = deck.text()
        // update all fields in one batch so we can’t accidentally skip one
        // due to auto-recalc or running state.
        if let start = newStart {
            deck.setFloatFields(row: card, [
                (1, Double(start.x)),
                (2, Double(start.y)),
                (3, Double(start.z))
            ])
        }
        if let end = newEnd {
            deck.setFloatFields(row: card, [
                (4, Double(end.x)),
                (5, Double(end.y)),
                (6, Double(end.z))
            ])
        }
        if let after = deck.card(at: card) {
            print("  after:  f=\(after.f)")
        }
        selectedIndex = card
        // force a table reload in case SwiftUI hasn’t yet flushed the change
        NotificationCenter.default.post(name: NSNotification.Name("DeckDidEdit"), object: deck)
        undoManager?.registerUndo(withTarget: deck) { d in
            d.restore(text: snapshot)
        }
        undoManager?.setActionName("Move card \(card)")
    }
    /// View displayed when the Smith Chart tab is selected.
    private func smithChartTab(_ result: SimulationResult) -> some View {
        return ZStack {
            if result.impedances.isEmpty {
                VStack(spacing: 8) {
                    Image(systemName: "waveform.circle")
                        .font(.system(size: 32))
                        .foregroundStyle(.secondary)
                    Text("No impedance data")
                        .foregroundStyle(.secondary)
                    Text("Run a simulation to compute antenna input impedances.")
                        .font(.caption)
                        .foregroundStyle(.tertiary)
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity)
            } else {
                // Convert impedances to format expected by SmithChartView
                let impedanceArrays = result.impedances.map {
                    (zr: [$0.zr], zi: [$0.zi])
                }
                SmithChartView(impedances: impedanceArrays)
                    .frame(maxWidth: .infinity, maxHeight: .infinity)
            }
        }
    }}

// MARK: – ResultTab

private enum ResultTab: String, CaseIterable, Identifiable {
    case geometry = "Geometry"
    case pattern  = "Pattern"
    case smith    = "Smith Chart"

    var id: String { rawValue }
    var label: String { rawValue }
}

// MARK: – Legend view

/// Displays a small gradient bar showing the mapping from gain values to the
/// colours used in the PatternView.
private struct GainLegend: View {
    let minGain: Double
    let maxGain: Double

    var body: some View {
        VStack(spacing: 4) {
            HStack {
                Text(String(format: "%.1f dBi", minGain))
                    .font(.caption2)
                Spacer()
                Text(String(format: "%.1f dBi", maxGain))
                    .font(.caption2)
            }
            Rectangle()
                .fill(LinearGradient(
                    gradient: Gradient(colors: [
                        PatternView.swiftUIColor(forNorm: 0),
                        PatternView.swiftUIColor(forNorm: 1)
                    ]),
                    startPoint: .leading,
                    endPoint: .trailing))
                .frame(height: 8)
                .cornerRadius(4)
        }
        .padding(4)
    }
}

// MARK: – MonospaceTextView

/// NSViewRepresentable wrapping NSTextView for displaying large monospace text.
/// SwiftUI's Text/ScrollView combo degrades badly for long NEC output (~1000+ lines).
private struct MonospaceTextView: NSViewRepresentable {

    let text: String

    func makeNSView(context: Context) -> NSScrollView {
        let scrollView = NSTextView.scrollableTextView()
        if let tv = scrollView.documentView as? NSTextView {
            tv.isEditable      = false
            tv.isSelectable    = true
            tv.font            = NSFont.monospacedSystemFont(ofSize: 11, weight: .regular)
            tv.backgroundColor = NSColor.textBackgroundColor
            tv.textColor       = NSColor.textColor
            tv.string          = text
        }
        return scrollView
    }

    func updateNSView(_ scrollView: NSScrollView, context: Context) {
        guard let tv = scrollView.documentView as? NSTextView else { return }
        if tv.string != text {
            tv.string = text
            // Scroll to top on new result
            tv.scrollToBeginningOfDocument(nil)
        }
    }
}
